# Generated by Django 4.2.7 on 2025-11-09 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifDeclic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('departement', models.CharField(blank=True, max_length=3, null=True, verbose_name='Département')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('valeur_objectif', models.PositiveIntegerField(verbose_name='Objectif annuel (personnes)')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_declic', to='rap_app.centre', verbose_name='Centre de formation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Objectif Déclic (centre)',
                'verbose_name_plural': 'Objectifs Déclic (centres)',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Declic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('type_declic', models.CharField(choices=[('info_collective', 'Information collective'), ('atelier_1', 'Atelier 1'), ('atelier_2', 'Atelier 2'), ('atelier_3', 'Atelier 3'), ('atelier_4', 'Atelier 4'), ('atelier_5', 'Atelier 5'), ('atelier_6', 'Atelier 6'), ('autre', 'Autre activité Déclic')], max_length=40, verbose_name='Type d’activité')),
                ('date_declic', models.DateField(help_text='Date de la séance ou de la semaine concernée', verbose_name='Date')),
                ('nombre_places_ouvertes', models.PositiveIntegerField(default=0, verbose_name='Places ouvertes (IC)')),
                ('nombre_prescriptions', models.PositiveIntegerField(default=0, verbose_name='Prescriptions (IC)')),
                ('nb_presents_info', models.PositiveIntegerField(default=0, verbose_name='Présents (IC)')),
                ('nb_absents_info', models.PositiveIntegerField(default=0, verbose_name='Absents (IC)')),
                ('nb_adhesions', models.PositiveIntegerField(default=0, verbose_name='Adhésions (IC)')),
                ('nb_inscrits_declic', models.PositiveIntegerField(default=0, verbose_name='Inscrits (Atelier)')),
                ('nb_presents_declic', models.PositiveIntegerField(default=0, verbose_name='Présents (Atelier)')),
                ('nb_absents_declic', models.PositiveIntegerField(default=0, verbose_name='Absents (Atelier)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire / notes')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declics', to='rap_app.centre', verbose_name='Centre de formation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Séance Déclic',
                'verbose_name_plural': 'Séances Déclic',
                'ordering': ['-date_declic', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='objectifdeclic',
            constraint=models.UniqueConstraint(fields=('centre', 'annee'), name='uniq_objectif_declic_centre_annee'),
        ),
        migrations.AddIndex(
            model_name='declic',
            index=models.Index(fields=['centre'], name='rap_app_dec_centre__be81d2_idx'),
        ),
        migrations.AddIndex(
            model_name='declic',
            index=models.Index(fields=['date_declic'], name='rap_app_dec_date_de_b171a1_idx'),
        ),
        migrations.AddIndex(
            model_name='declic',
            index=models.Index(fields=['type_declic'], name='rap_app_dec_type_de_a36876_idx'),
        ),
    ]
