# Generated by Django 4.2.7 on 2025-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_objectifdeclic_declic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cette adresse email existe déjà.'}, help_text='Adresse utilisée pour la connexion.', max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrateur'), ('admin', 'Administrateur'), ('staff', 'Membre du staff'), ('staff_read', 'Staff lecture seule'), ('prepa_staff', 'Staff PrépaComp'), ('declic_staff', 'Staff Déclic'), ('stagiaire', 'Stagiaire'), ('candidat', 'Candidat'), ('candidatuser', 'Candidat validé'), ('test', 'Test')], db_index=True, default='stagiaire', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AddIndex(
            model_name='objectifdeclic',
            index=models.Index(fields=['centre', 'annee'], name='rap_app_obj_centre__281601_idx'),
        ),
    ]
