# Generated by Django 4.2.7 on 2025-11-15 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0004_alter_customuser_options_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('type_prepa', models.CharField(choices=[('info_collective', 'Information collective'), ('atelier_1', 'Atelier 1'), ('atelier_2', 'Atelier 2'), ('atelier_3', 'Atelier 3'), ('atelier_4', 'Atelier 4'), ('atelier_5', 'Atelier 5'), ('atelier_6', 'Atelier 6'), ('autre', 'Autre activité Prépa')], max_length=40, verbose_name='Type d’activité')),
                ('date_prepa', models.DateField(help_text='Date de la séance ou de la semaine concernée', verbose_name='Date')),
                ('nombre_places_ouvertes', models.PositiveIntegerField(default=0, verbose_name='Places ouvertes (IC)')),
                ('nombre_prescriptions', models.PositiveIntegerField(default=0, verbose_name='Prescriptions (IC)')),
                ('nb_presents_info', models.PositiveIntegerField(default=0, verbose_name='Présents (IC)')),
                ('nb_absents_info', models.PositiveIntegerField(default=0, verbose_name='Absents (IC)')),
                ('nb_adhesions', models.PositiveIntegerField(default=0, verbose_name='Adhésions (IC)')),
                ('nb_inscrits_prepa', models.PositiveIntegerField(default=0, verbose_name='Inscrits (Atelier)')),
                ('nb_presents_prepa', models.PositiveIntegerField(default=0, verbose_name='Présents (Atelier)')),
                ('nb_absents_prepa', models.PositiveIntegerField(default=0, verbose_name='Absents (Atelier)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire / notes')),
            ],
            options={
                'verbose_name': 'Séance Prépa',
                'verbose_name_plural': 'Séances Prépa',
                'ordering': ['-date_prepa', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='prepa2',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='prepa2',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prepa2',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='objectifprepa',
            options={'ordering': ['-annee'], 'verbose_name': 'Objectif Prépa (centre)', 'verbose_name_plural': 'Objectifs Prépa (centres)'},
        ),
        migrations.RemoveConstraint(
            model_name='objectifprepa',
            name='uniq_objectif_centre_annee',
        ),
        migrations.AddIndex(
            model_name='objectifprepa',
            index=models.Index(fields=['centre', 'annee'], name='rap_app_obj_centre__858d7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectifprepa',
            constraint=models.UniqueConstraint(fields=('centre', 'annee'), name='uniq_objectif_prepa_centre_annee'),
        ),
        migrations.DeleteModel(
            name='Prepa2',
        ),
        migrations.AddField(
            model_name='prepa',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepas', to='rap_app.centre', verbose_name='Centre de formation'),
        ),
        migrations.AddField(
            model_name='prepa',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='prepa',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddIndex(
            model_name='prepa',
            index=models.Index(fields=['centre'], name='rap_app_pre_centre__973752_idx'),
        ),
        migrations.AddIndex(
            model_name='prepa',
            index=models.Index(fields=['date_prepa'], name='rap_app_pre_date_pr_034123_idx'),
        ),
        migrations.AddIndex(
            model_name='prepa',
            index=models.Index(fields=['type_prepa'], name='rap_app_pre_type_pr_e10bd9_idx'),
        ),
    ]
