# Generated by Django 4.2.7 on 2025-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0005_prepa_remove_prepa2_centre_remove_prepa2_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declic',
            options={'ordering': ['-date_declic', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='declic',
            name='rap_app_dec_centre__be81d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='declic',
            name='rap_app_dec_date_de_b171a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='declic',
            name='rap_app_dec_type_de_a36876_idx',
        ),
        migrations.RemoveField(
            model_name='declic',
            name='nb_absents_info',
        ),
        migrations.RemoveField(
            model_name='declic',
            name='nb_adhesions',
        ),
        migrations.RemoveField(
            model_name='declic',
            name='nb_presents_info',
        ),
        migrations.RemoveField(
            model_name='declic',
            name='nombre_places_ouvertes',
        ),
        migrations.RemoveField(
            model_name='declic',
            name='nombre_prescriptions',
        ),
        migrations.AlterField(
            model_name='declic',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declic',
            name='date_declic',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='declic',
            name='nb_absents_declic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='declic',
            name='nb_inscrits_declic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='declic',
            name='nb_presents_declic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='declic',
            name='type_declic',
            field=models.CharField(choices=[('atelier_1', 'Atelier 1'), ('atelier_2', 'Atelier 2'), ('atelier_3', 'Atelier 3'), ('atelier_4', 'Atelier 4'), ('atelier_5', 'Atelier 5'), ('atelier_6', 'Atelier 6'), ('autre', 'Autre activité Déclic')], max_length=40),
        ),
    ]
