# Generated by Django 4.2.7 on 2025-11-16 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rap_app.models.cvtheque


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0006_alter_declic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('LM', 'Lettre de motivation'), ('DIPLOME', 'Diplôme/Certificat'), ('AUTRE', 'Autre document')], default='CV', max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(help_text='Formats acceptés : PDF, DOC, DOCX (max. 5Mo)', upload_to=rap_app.models.cvtheque.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Fichier')),
                ('titre', models.CharField(help_text='Ex: CV 2023, Lettre de motivation pour poste X', max_length=255, verbose_name='Titre du document')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('est_public', models.BooleanField(default=False, help_text='Ce document peut-il être visible par les recruteurs ?', verbose_name='Visible par les recruteurs')),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-clés pour la recherche (séparés par des virgules)', verbose_name='Mots-clés')),
                ('consentement_stockage_cv', models.BooleanField(default=False, help_text='Le candidat accepte que son CV soit stocké dans la CVThèque.')),
                ('consentement_transmission_cv', models.BooleanField(default=False, help_text='Le candidat accepte que son CV soit transmis à un employeur.')),
                ('date_consentement_cv', models.DateTimeField(blank=True, help_text='Date du consentement donné ou retiré.', null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='rap_app.candidat', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'CVthèque',
                'verbose_name_plural': 'CVthèque',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.AddConstraint(
            model_name='cvtheque',
            constraint=models.UniqueConstraint(fields=('candidat', 'titre'), name='unique_cv_per_candidat'),
        ),
    ]
