# Generated by Django 4.2.7 on 2025-11-16 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0007_cvtheque_cvtheque_unique_cv_per_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtheque',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvtheque',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cvtheque',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='cvtheque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='cvtheque',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
