# Generated by Django 4.2.7 on 2026-03-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0009_delete_cerfaremuneration_alter_cerfacontrat_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appairage',
            name='unique_appairage',
        ),
        migrations.AddConstraint(
            model_name='appairage',
            constraint=models.UniqueConstraint(condition=models.Q(('formation__isnull', False)), fields=('candidat', 'partenaire', 'formation'), name='unique_appairage_avec_formation'),
        ),
        migrations.AddConstraint(
            model_name='appairage',
            constraint=models.UniqueConstraint(condition=models.Q(('formation__isnull', True)), fields=('candidat', 'partenaire'), name='unique_appairage_sans_formation'),
        ),
    ]
