# Generated by Django 4.2.7 on 2026-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0013_candidat_parcours_phase_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="demande_compte_statut",
            field=models.CharField(
                choices=[
                    ("aucune", "Aucune demande"),
                    ("en_attente", "Demande en attente"),
                    ("acceptee", "Demande acceptée"),
                    ("refusee", "Demande refusée"),
                ],
                default="aucune",
                help_text="Suivi minimal de la demande de création de compte utilisateur associée au candidat.",
                max_length=20,
                verbose_name="Statut de demande de compte",
            ),
        ),
    ]
