# Generated by Django 4.2.7 on 2026-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0016_candidat_rgpd_consent_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="rgpd_creation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual_admin", "Création manuelle staff/admin"),
                    ("self_service", "Création par la personne concernée"),
                    ("import", "Import"),
                ],
                help_text="Permet de distinguer une fiche créée manuellement, en self-service ou via import.",
                max_length=32,
                null=True,
                verbose_name="Origine RGPD de création",
            ),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="rgpd_legal_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consentement", "Consentement"),
                    ("mesures_precontractuelles", "Mesures précontractuelles"),
                    ("interet_legitime", "Intérêt légitime"),
                    ("obligation_legale", "Obligation légale"),
                    ("mission_interet_public", "Mission d'intérêt public"),
                    ("interets_vitaux", "Intérêts vitaux"),
                ],
                help_text="Base légale principale justifiant le traitement des données personnelles.",
                max_length=40,
                null=True,
                verbose_name="Base légale RGPD",
            ),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="rgpd_notice_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_requise", "Notification non requise"),
                    ("a_notifier", "Notification à envoyer"),
                    ("notifiee", "Notification envoyée"),
                ],
                help_text="Suivi de l'information transmise à la personne concernée lorsque nécessaire.",
                max_length=20,
                null=True,
                verbose_name="Statut de notification RGPD",
            ),
        ),
    ]
