# Generated by Django 4.2.7 on 2026-03-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0018_candidat_manual_status_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="parcours_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postulant", "Candidat"),
                    ("inscrit_valide", "Inscrit GESPERS"),
                    ("stagiaire_en_formation", "En formation"),
                    ("sorti", "Sortie / fin de formation"),
                    ("abandon", "Abandon"),
                ],
                db_index=True,
                help_text="Nouvelle phase métier cible. Ajoutée en compatibilité sans remplacer immédiatement le statut legacy.",
                max_length=32,
                null=True,
                verbose_name="Phase de parcours",
            ),
        ),
    ]
