# Generated by Django 4.2.7 on 2026-03-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rap_app", "0019_alter_candidat_parcours_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagiairePrepa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de la dernière modification",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name="Actif"),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=120, verbose_name="Prénom")),
                ("telephone", models.CharField(blank=True, max_length=30, null=True, verbose_name="Téléphone")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                (
                    "statut_parcours",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de parcours"),
                            ("en_parcours", "En parcours"),
                            ("parcours_termine", "Parcours terminé"),
                            ("abandon", "Abandon"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=24,
                        verbose_name="Statut de parcours",
                    ),
                ),
                ("date_entree_parcours", models.DateField(blank=True, null=True, verbose_name="Date d'entrée parcours")),
                ("date_sortie_parcours", models.DateField(blank=True, null=True, verbose_name="Date de sortie parcours")),
                ("commentaire_suivi", models.TextField(blank=True, null=True, verbose_name="Commentaire de suivi")),
                ("motif_abandon", models.CharField(blank=True, max_length=255, null=True, verbose_name="Motif d'abandon")),
                ("atelier_1_realise", models.BooleanField(default=False, verbose_name="Atelier 1 réalisé")),
                ("atelier_2_realise", models.BooleanField(default=False, verbose_name="Atelier 2 réalisé")),
                ("atelier_3_realise", models.BooleanField(default=False, verbose_name="Atelier 3 réalisé")),
                ("atelier_4_realise", models.BooleanField(default=False, verbose_name="Atelier 4 réalisé")),
                ("atelier_5_realise", models.BooleanField(default=False, verbose_name="Atelier 5 réalisé")),
                ("atelier_6_realise", models.BooleanField(default=False, verbose_name="Atelier 6 réalisé")),
                ("atelier_autre_realise", models.BooleanField(default=False, verbose_name="Autre atelier réalisé")),
                ("date_atelier_1", models.DateField(blank=True, null=True, verbose_name="Date atelier 1")),
                ("date_atelier_2", models.DateField(blank=True, null=True, verbose_name="Date atelier 2")),
                ("date_atelier_3", models.DateField(blank=True, null=True, verbose_name="Date atelier 3")),
                ("date_atelier_4", models.DateField(blank=True, null=True, verbose_name="Date atelier 4")),
                ("date_atelier_5", models.DateField(blank=True, null=True, verbose_name="Date atelier 5")),
                ("date_atelier_6", models.DateField(blank=True, null=True, verbose_name="Date atelier 6")),
                ("date_atelier_autre", models.DateField(blank=True, null=True, verbose_name="Date autre atelier")),
                (
                    "centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stagiaires_prepa",
                        to="rap_app.centre",
                        verbose_name="Centre",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Utilisateur ayant créé l'enregistrement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stagiaireprepa_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "prepa_origine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stagiaires_prepa",
                        to="rap_app.prepa",
                        verbose_name="Prépa d'origine",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur ayant modifié l'enregistrement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_stagiaireprepa_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stagiaire Prépa",
                "verbose_name_plural": "Stagiaires Prépa",
                "ordering": ["nom", "prenom", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="stagiaireprepa",
            index=models.Index(fields=["is_active"], name="rap_app_stagiaireprepa_active_idx"),
        ),
        migrations.AddIndex(
            model_name="stagiaireprepa",
            index=models.Index(fields=["prepa_origine"], name="rap_app_sta_prepa_o_10dd7f_idx"),
        ),
        migrations.AddIndex(
            model_name="stagiaireprepa",
            index=models.Index(fields=["centre"], name="rap_app_sta_centre__df78a2_idx"),
        ),
        migrations.AddIndex(
            model_name="stagiaireprepa",
            index=models.Index(fields=["statut_parcours"], name="rap_app_sta_statut__07eb9d_idx"),
        ),
        migrations.AddIndex(
            model_name="stagiaireprepa",
            index=models.Index(fields=["nom", "prenom"], name="rap_app_sta_nom_7613b5_idx"),
        ),
    ]
