# Generated by Django 4.2.7 on 2026-03-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0021_prepa_formateur_animateur"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stagiaireprepa",
            name="rap_app_stagiaireprepa_active_idx",
        ),
        migrations.RenameIndex(
            model_name="stagiaireprepa",
            new_name="rap_app_sta_prepa_o_97e201_idx",
            old_name="rap_app_sta_prepa_o_10dd7f_idx",
        ),
        migrations.RenameIndex(
            model_name="stagiaireprepa",
            new_name="rap_app_sta_centre__edbe57_idx",
            old_name="rap_app_sta_centre__df78a2_idx",
        ),
        migrations.RenameIndex(
            model_name="stagiaireprepa",
            new_name="rap_app_sta_statut__e7747f_idx",
            old_name="rap_app_sta_statut__07eb9d_idx",
        ),
        migrations.RenameIndex(
            model_name="stagiaireprepa",
            new_name="rap_app_sta_nom_7dc2a9_idx",
            old_name="rap_app_sta_nom_7613b5_idx",
        ),
        migrations.AlterField(
            model_name="stagiaireprepa",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Utilisateur ayant créé l'enregistrement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="stagiaireprepa",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Dernier utilisateur ayant modifié l'enregistrement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
    ]
