# Generated by Django 4.2.7 on 2026-03-24 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0023_merge_20260324_1530"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="participantdeclic",
            new_name="rap_app_par_declic__b476e4_idx",
            old_name="rap_app_par_declic__8ff40b_idx",
        ),
        migrations.RenameIndex(
            model_name="participantdeclic",
            new_name="rap_app_par_centre__7c3f10_idx",
            old_name="rap_app_par_centre__2d4a48_idx",
        ),
        migrations.RenameIndex(
            model_name="participantdeclic",
            new_name="rap_app_par_present_b4575b_idx",
            old_name="rap_app_par_present_3dc0e7_idx",
        ),
        migrations.RenameIndex(
            model_name="participantdeclic",
            new_name="rap_app_par_nom_7df509_idx",
            old_name="rap_app_par_nom_8661eb_idx",
        ),
        migrations.RemoveField(
            model_name="participantdeclic",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="participantdeclic",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="participantdeclic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date et heure de création de l'enregistrement",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="participantdeclic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Utilisateur ayant créé l'enregistrement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="participantdeclic",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indique si l'objet est actif ou archivé",
                verbose_name="Actif",
            ),
        ),
        migrations.AlterField(
            model_name="participantdeclic",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date et heure de la dernière modification",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="participantdeclic",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Dernier utilisateur ayant modifié l'enregistrement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
    ]
