# Generated by Django 4.2.7 on 2026-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0028_alter_partenaire_idcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='dernier_diplome_prepare_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text='Code CERFA du dernier diplome ou titre prepare.', max_length=2, null=True, verbose_name='Dernier diplome prepare CERFA'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='derniere_classe_code',
            field=models.CharField(blank=True, choices=[('01', '01 - Derniere annee du cycle suivie et diplome obtenu'), ('11', '11 - 1ere annee validee'), ('12', '12 - 1ere annee non validee'), ('21', '21 - 2e annee validee'), ('22', '22 - 2e annee non validee'), ('31', '31 - 3e annee validee'), ('32', '32 - 3e annee non validee'), ('40', "40 - 1er cycle de l'enseignement secondaire acheve"), ('41', '41 - Interruption en 3e'), ('42', '42 - Interruption en 4e')], help_text='Code CERFA de la derniere classe ou annee suivie.', max_length=2, null=True, verbose_name='Derniere classe CERFA'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplome_plus_eleve_obtenu_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text='Code CERFA du diplome ou titre le plus eleve obtenu.', max_length=2, null=True, verbose_name='Plus haut diplome obtenu CERFA'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='nationalite_code',
            field=models.CharField(blank=True, choices=[('1', '1 - Francaise'), ('2', '2 - Union europeenne'), ('3', '3 - Etranger hors Union europeenne')], help_text='Code CERFA de nationalite.', max_length=2, null=True, verbose_name='Nationalite CERFA'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='regime_social_code',
            field=models.CharField(blank=True, choices=[('1', '1 - MSA'), ('2', '2 - URSSAF')], help_text='Code CERFA du regime social.', max_length=1, null=True, verbose_name='Regime social CERFA'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='situation_avant_contrat_code',
            field=models.CharField(blank=True, choices=[('1', '1 - Scolaire'), ('2', '2 - Prepa apprentissage'), ('3', '3 - Etudiant'), ('4', "4 - Contrat d'apprentissage"), ('5', '5 - Contrat de professionnalisation'), ('6', '6 - Contrat aide'), ('7', '7 - En formation au CFA sous statut de stagiaire avant contrat'), ('8', '8 - En formation au CFA sans contrat suite a rupture'), ('9', '9 - Autres situations sous statut de stagiaire de la formation professionnelle'), ('10', '10 - Salarie'), ('11', "11 - Personne a la recherche d'un emploi"), ('12', '12 - Inactif')], help_text='Code CERFA de la situation avant contrat.', max_length=2, null=True, verbose_name='Situation avant contrat CERFA'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='type_contrat_code',
            field=models.CharField(blank=True, choices=[('11', "11 - Premier contrat d'apprentissage"), ('21', '21 - Nouveau contrat apres contrat termine chez le meme employeur'), ('22', '22 - Nouveau contrat apres contrat termine chez un autre employeur'), ('23', '23 - Nouveau contrat apres rupture'), ('31', "31 - Modification de la situation juridique de l'employeur"), ('32', "32 - Changement d'employeur dans le cadre d'un contrat saisonnier"), ('33', "33 - Prolongation suite a un echec a l'examen"), ('34', '34 - Prolongation suite a la reconnaissance RQTH'), ('35', '35 - Diplome supplementaire prepare'), ('36', '36 - Autres changements'), ('37', "37 - Modification du lieu d'execution du contrat"), ('38', '38 - Modification du lieu principal de formation theorique')], help_text='Code CERFA du type de contrat ou avenant.', max_length=2, null=True, verbose_name='Type de contrat CERFA'),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_dernier_diplome_prepare_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text='Code CERFA du dernier diplome prepare.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_derniere_annee_suivie_code',
            field=models.CharField(blank=True, choices=[('01', '01 - Derniere annee du cycle suivie et diplome obtenu'), ('11', '11 - 1ere annee validee'), ('12', '12 - 1ere annee non validee'), ('21', '21 - 2e annee validee'), ('22', '22 - 2e annee non validee'), ('31', '31 - 3e annee validee'), ('32', '32 - 3e annee non validee'), ('40', "40 - 1er cycle de l'enseignement secondaire acheve"), ('41', '41 - Interruption en 3e'), ('42', '42 - Interruption en 4e')], help_text='Code CERFA de la derniere classe ou annee suivie.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_nationalite_code',
            field=models.CharField(blank=True, choices=[('1', '1 - Francaise'), ('2', '2 - Union europeenne'), ('3', '3 - Etranger hors Union europeenne')], help_text='Code CERFA de nationalite.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_plus_haut_diplome_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text='Code CERFA du plus haut diplome obtenu.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_regime_social_code',
            field=models.CharField(blank=True, choices=[('1', '1 - MSA'), ('2', '2 - URSSAF')], help_text='Code CERFA du regime social.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_situation_avant_code',
            field=models.CharField(blank=True, choices=[('1', '1 - Scolaire'), ('2', '2 - Prepa apprentissage'), ('3', '3 - Etudiant'), ('4', "4 - Contrat d'apprentissage"), ('5', '5 - Contrat de professionnalisation'), ('6', '6 - Contrat aide'), ('7', '7 - En formation au CFA sous statut de stagiaire avant contrat'), ('8', '8 - En formation au CFA sans contrat suite a rupture'), ('9', '9 - Autres situations sous statut de stagiaire de la formation professionnelle'), ('10', '10 - Salarie'), ('11', "11 - Personne a la recherche d'un emploi"), ('12', '12 - Inactif')], help_text='Code CERFA de la situation avant contrat.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='diplome_vise_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text='Code CERFA du diplome ou titre vise.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='employeur_specifique_code',
            field=models.CharField(blank=True, choices=[('0', '0 - Aucun de ces cas'), ('1', '1 - Entreprise de travail temporaire'), ('2', "2 - Groupement d'employeurs"), ('3', '3 - Employeur saisonnier'), ('4', '4 - Apprentissage familial')], help_text="Code CERFA de l'employeur specifique.", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='employeur_type_code',
            field=models.CharField(blank=True, choices=[('11', '11 - Entreprise inscrite au repertoire des metiers'), ('12', '12 - Entreprise inscrite uniquement au registre du commerce et des societes'), ('13', '13 - Entreprise relevant de la mutualite sociale agricole'), ('14', '14 - Profession liberale'), ('15', '15 - Association'), ('16', '16 - Autre employeur prive'), ('21', "21 - Service de l'Etat"), ('22', '22 - Commune'), ('23', '23 - Departement'), ('24', '24 - Region'), ('25', '25 - Etablissement public hospitalier'), ('26', "26 - Etablissement public local d'enseignement"), ('27', "27 - Etablissement public administratif de l'Etat"), ('28', '28 - Etablissement public administratif local'), ('29', '29 - Autre employeur public'), ('30', '30 - Etablissement public industriel et commercial')], help_text="Code CERFA du type d'employeur.", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='maitre1_niveau_diplome_code',
            field=models.CharField(blank=True, choices=[('0', '0 - Aucun'), ('3', '3 - CAP, BEP'), ('4', '4 - Baccalaureat'), ('5', '5 - DEUG, BTS, DUT, DEUST'), ('6', '6 - Licence, licence professionnelle, BUT, Maitrise'), ('7', "7 - Master, DEA, DESS, diplome d'ingenieur"), ('8', '8 - Doctorat, HDR')], help_text='Code CERFA du niveau de diplome du maitre 1.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='maitre2_niveau_diplome_code',
            field=models.CharField(blank=True, choices=[('0', '0 - Aucun'), ('3', '3 - CAP, BEP'), ('4', '4 - Baccalaureat'), ('5', '5 - DEUG, BTS, DUT, DEUST'), ('6', '6 - Licence, licence professionnelle, BUT, Maitrise'), ('7', "7 - Master, DEA, DESS, diplome d'ingenieur"), ('8', '8 - Doctorat, HDR')], help_text='Code CERFA du niveau de diplome du maitre 2.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='type_contrat_code',
            field=models.CharField(blank=True, choices=[('11', "11 - Premier contrat d'apprentissage"), ('21', '21 - Nouveau contrat apres contrat termine chez le meme employeur'), ('22', '22 - Nouveau contrat apres contrat termine chez un autre employeur'), ('23', '23 - Nouveau contrat apres rupture'), ('31', "31 - Modification de la situation juridique de l'employeur"), ('32', "32 - Changement d'employeur dans le cadre d'un contrat saisonnier"), ('33', "33 - Prolongation suite a un echec a l'examen"), ('34', '34 - Prolongation suite a la reconnaissance RQTH'), ('35', '35 - Diplome supplementaire prepare'), ('36', '36 - Autres changements'), ('37', "37 - Modification du lieu d'execution du contrat"), ('38', '38 - Modification du lieu principal de formation theorique')], help_text='Code CERFA du type de contrat ou avenant.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='type_derogation_code',
            field=models.CharField(blank=True, choices=[('11', '11 - Age inferieur a 16 ans'), ('12', '12 - Age superieur a 29 ans'), ('21', '21 - Reduction de la duree'), ('22', '22 - Allongement de la duree'), ('50', '50 - Cumul de derogations'), ('60', '60 - Autre derogation')], help_text='Code CERFA du type de derogation.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='diplome_vise_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text="Code CERFA du diplome ou titre vise par l'apprenti.", max_length=2, null=True, verbose_name='Diplome vise CERFA'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='employeur_specifique_code',
            field=models.CharField(blank=True, choices=[('0', '0 - Aucun de ces cas'), ('1', '1 - Entreprise de travail temporaire'), ('2', "2 - Groupement d'employeurs"), ('3', '3 - Employeur saisonnier'), ('4', '4 - Apprentissage familial')], help_text="Code CERFA de l'employeur specifique.", max_length=1, null=True, verbose_name='Employeur specifique CERFA'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_niveau_diplome_code',
            field=models.CharField(blank=True, choices=[('0', '0 - Aucun'), ('3', '3 - CAP, BEP'), ('4', '4 - Baccalaureat'), ('5', '5 - DEUG, BTS, DUT, DEUST'), ('6', '6 - Licence, licence professionnelle, BUT, Maitrise'), ('7', "7 - Master, DEA, DESS, diplome d'ingenieur"), ('8', '8 - Doctorat, HDR')], help_text="Code CERFA du niveau de diplome du maitre d'apprentissage n°1.", max_length=1, null=True, verbose_name='Maître d’apprentissage n°1 - Niveau CERFA'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_niveau_diplome_code',
            field=models.CharField(blank=True, choices=[('0', '0 - Aucun'), ('3', '3 - CAP, BEP'), ('4', '4 - Baccalaureat'), ('5', '5 - DEUG, BTS, DUT, DEUST'), ('6', '6 - Licence, licence professionnelle, BUT, Maitrise'), ('7', "7 - Master, DEA, DESS, diplome d'ingenieur"), ('8', '8 - Doctorat, HDR')], help_text="Code CERFA du niveau de diplome du maitre d'apprentissage n°2.", max_length=1, null=True, verbose_name='Maître d’apprentissage n°2 - Niveau CERFA'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='type_employeur_code',
            field=models.CharField(blank=True, choices=[('11', '11 - Entreprise inscrite au repertoire des metiers'), ('12', '12 - Entreprise inscrite uniquement au registre du commerce et des societes'), ('13', '13 - Entreprise relevant de la mutualite sociale agricole'), ('14', '14 - Profession liberale'), ('15', '15 - Association'), ('16', '16 - Autre employeur prive'), ('21', "21 - Service de l'Etat"), ('22', '22 - Commune'), ('23', '23 - Departement'), ('24', '24 - Region'), ('25', '25 - Etablissement public hospitalier'), ('26', "26 - Etablissement public local d'enseignement"), ('27', "27 - Etablissement public administratif de l'Etat"), ('28', '28 - Etablissement public administratif local'), ('29', '29 - Autre employeur public'), ('30', '30 - Etablissement public industriel et commercial')], help_text="Code CERFA du type d'employeur.", max_length=2, null=True, verbose_name="Type d'employeur CERFA"),
        ),
    ]
