# Generated by Django 4.2.7 on 2026-03-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0029_candidat_dernier_diplome_prepare_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='dernier_diplome_prepare',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='derniere_classe',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='diplome_plus_eleve_obtenu',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='regime_social',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='situation_avant_contrat',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='employeur_specifique',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='maitre1_niveau_diplome',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='maitre2_niveau_diplome',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='type_employeur',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='dernier_diplome_prepare_code',
            field=models.CharField(blank=True, choices=[('13', '13 - Aucun diplome ni titre professionnel'), ('25', '25 - Diplome national du Brevet'), ('26', '26 - Certificat de formation generale'), ('33', '33 - CAP'), ('34', '34 - BEP'), ('35', '35 - Certificat de specialisation'), ('38', '38 - Autre diplome ou titre de niveau CAP/BEP'), ('41', '41 - Baccalaureat professionnel'), ('42', '42 - Baccalaureat general'), ('43', '43 - Baccalaureat technologique'), ('44', '44 - Diplome de specialisation professionnelle'), ('49', '49 - Autre diplome ou titre de niveau bac'), ('54', '54 - Brevet de Technicien Superieur'), ('55', '55 - Diplome Universitaire de technologie'), ('58', '58 - Autre diplome ou titre de niveau bac+2'), ('62', '62 - Licence professionnelle'), ('63', '63 - Licence generale'), ('64', '64 - Bachelor universitaire de technologie BUT'), ('69', '69 - Autre diplome ou titre de niveau bac+3 ou 4'), ('73', '73 - Master'), ('75', "75 - Diplome d'ingenieur"), ('76', "76 - Diplome d'ecole de commerce"), ('79', '79 - Autre diplome ou titre de niveau bac+5 ou plus'), ('80', '80 - Doctorat')], help_text='Code CERFA du dernier diplome ou titre prepare par le candidat.', max_length=2, null=True, verbose_name='Dernier diplome prepare CERFA'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nationalite_code',
            field=models.CharField(blank=True, choices=[('1', '1 - Francaise'), ('2', '2 - Union europeenne'), ('3', '3 - Etranger hors Union europeenne')], help_text="Code CERFA de la nationalite de l'apprenti.", max_length=2, null=True, verbose_name='Nationalite CERFA'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='regime_social_code',
            field=models.CharField(blank=True, choices=[('1', '1 - MSA'), ('2', '2 - URSSAF')], help_text='Code CERFA du regime social de rattachement.', max_length=1, null=True, verbose_name='Regime social CERFA'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='situation_actuelle',
            field=models.CharField(blank=True, help_text='Champ metier libre conserve hors codification CERFA.', max_length=255, null=True, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='type_employeur_code',
            field=models.CharField(blank=True, choices=[('11', '11 - Entreprise inscrite au repertoire des metiers'), ('12', '12 - Entreprise inscrite uniquement au registre du commerce et des societes'), ('13', '13 - Entreprise relevant de la mutualite sociale agricole'), ('14', '14 - Profession liberale'), ('15', '15 - Association'), ('16', '16 - Autre employeur prive'), ('21', "21 - Service de l'Etat"), ('22', '22 - Commune'), ('23', '23 - Departement'), ('24', '24 - Region'), ('25', '25 - Etablissement public hospitalier'), ('26', "26 - Etablissement public local d'enseignement"), ('27', "27 - Etablissement public administratif de l'Etat"), ('28', '28 - Etablissement public administratif local'), ('29', '29 - Autre employeur public'), ('30', '30 - Etablissement public industriel et commercial')], help_text="Code CERFA complet du type d'employeur.", max_length=2, null=True, verbose_name="Type d'employeur CERFA"),
        ),
    ]
