# Generated by Django 4.2.7 on 2026-03-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0030_remove_candidat_dernier_diplome_prepare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='situation_actuelle',
        ),
    ]
