# Generated by Django 4.2.7 on 2026-03-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0038_cerfacontrat_opco_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='duree_inscription_france_travail_mois',
            field=models.PositiveIntegerField(blank=True, help_text="Durée déclarée d'inscription à France Travail, en mois.", null=True, verbose_name="Durée d'inscription France Travail (mois)"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='inscrit_france_travail',
            field=models.BooleanField(default=False, help_text='Information de parcours durable utile au pré-remplissage du CERFA professionnalisation.', verbose_name='Inscrit France Travail'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='numero_inscription_france_travail',
            field=models.CharField(blank=True, help_text="Numéro d'inscription à France Travail conservé sur la fiche candidat.", max_length=100, null=True, verbose_name="Numéro d'inscription France Travail"),
        ),
    ]
