# Generated by Django 4.2.7 on 2026-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0039_candidat_duree_inscription_france_travail_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfacontrat',
            name='apprenti_inscrit_france_travail',
            field=models.BooleanField(blank=True, help_text='Indique explicitement si le beneficiaire est inscrit a France Travail.', null=True),
        ),
    ]
