# Generated by Django 4.2.7 on 2026-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0040_cerfacontrat_apprenti_inscrit_france_travail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='type_contrat_code',
            field=models.CharField(blank=True, help_text='Code snapshot du type de contrat ou avenant CERFA. Le libelle exact depend du type de contrat vise : apprentissage ou professionnalisation.', max_length=2, null=True, verbose_name='Type de contrat CERFA'),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='type_contrat_code',
            field=models.CharField(blank=True, help_text='Code CERFA du type de contrat ou avenant. La nomenclature depend du type de CERFA (apprentissage ou professionnalisation).', max_length=2, null=True),
        ),
    ]
