# Generated by Django 4.2.7 on 2026-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0041_alter_candidat_type_contrat_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='type_qualification_visee',
            field=models.CharField(blank=True, choices=[('1', "1 - Certification enregistree au RNCP autre qu'un CQP"), ('2', '2 - Certificat de qualification professionnelle (CQP)'), ('3', "3 - Qualification reconnue dans les classifications d'une convention collective nationale"), ('4', "4 - Action delivree dans le cadre du contrat de professionnalisation experimental prevu en application du VI de l'article 28 de la loi n° 2018-771 du 5 septembre 2018"), ('5', '5 - Action de pre-qualification ou de pre-formation abroge'), ('6', "6 - Certification inscrite au repertoire specifique prevu a l'article L. 6113-6 du code du travail abroge"), ('7', '7 - Autre abroge'), ('8', "8 - Certification ou qualification professionnelle visee dans le cadre de l'experimentation associant des actions de validation des acquis de l'experience mentionnee a l'article 11 de la loi n° 2022-1598 du 21 decembre 2022")], help_text='Code de qualification visée utile au pré-remplissage du CERFA professionnalisation.', max_length=1, null=True, verbose_name='Type de qualification visée'),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='type_qualification_visee',
            field=models.CharField(blank=True, choices=[('1', "1 - Certification enregistree au RNCP autre qu'un CQP"), ('2', '2 - Certificat de qualification professionnelle (CQP)'), ('3', "3 - Qualification reconnue dans les classifications d'une convention collective nationale"), ('4', "4 - Action delivree dans le cadre du contrat de professionnalisation experimental prevu en application du VI de l'article 28 de la loi n° 2018-771 du 5 septembre 2018"), ('5', '5 - Action de pre-qualification ou de pre-formation abroge'), ('6', "6 - Certification inscrite au repertoire specifique prevu a l'article L. 6113-6 du code du travail abroge"), ('7', '7 - Autre abroge'), ('8', "8 - Certification ou qualification professionnelle visee dans le cadre de l'experimentation associant des actions de validation des acquis de l'experience mentionnee a l'article 11 de la loi n° 2022-1598 du 21 decembre 2022")], help_text='Type de qualification visee pour le CERFA professionnalisation.', max_length=1, null=True),
        ),
    ]
