# Generated by Django 4.2.7 on 2026-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0042_formation_type_qualification_visee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='specialite_formation',
            field=models.CharField(blank=True, help_text='Code NSF à 3 chiffres utilisé pour la spécialité de formation dans le CERFA professionnalisation.', max_length=3, null=True, verbose_name='Code NSF spécialité de formation'),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='specialite_formation',
            field=models.CharField(blank=True, help_text='Code NSF de specialite de formation pour le CERFA professionnalisation.', max_length=3, null=True),
        ),
    ]
