# Generated by Django 4.2.7 on 2026-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0043_formation_specialite_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='organisme_declaration_activite',
            field=models.CharField(blank=True, help_text="Numéro de déclaration d'activité de l'organisme de formation.", max_length=50, null=True, verbose_name="Déclaration d'activité"),
        ),
    ]
