# Generated by Django 4.2.7 on 2026-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0045_alter_cerfacontrat_specialite_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerfacontrat',
            name='specialite_formation',
            field=models.CharField(blank=True, choices=[('200', '200 - Technologies industrielles fondamentales'), ('201', '201 - Technologies de commandes des transformations industrielles'), ('221', '221 - Agro-alimentaire, alimentation, cuisine'), ('227', '227 - Energie, genie climatique'), ('230', '230 - Genie civil, construction, bois'), ('231', '231 - Mines et carrieres, genie civil, topographie'), ('232', '232 - Batiment : construction et couverture'), ('233', '233 - Batiment : finitions'), ('234', "234 - Travail du bois et de l'ameublement"), ('250', '250 - Specialites pluritechnologiques mecanique-electricite'), ('251', '251 - Mecanique generale et de precision, usinage'), ('252', '252 - Moteurs et mecanique auto'), ('255', '255 - Electricite, electronique'), ('310', '310 - Specialites plurivalentes des echanges et de la gestion'), ('311', '311 - Transport, manutention, magasinage'), ('312', '312 - Commerce, vente'), ('314', '314 - Comptabilite, gestion'), ('315', "315 - Ressources humaines, gestion du personnel, gestion de l'emploi"), ('320', '320 - Specialites plurivalentes de la communication'), ('321', '321 - Journalisme et communication'), ('326', "326 - Informatique, traitement de l'information, reseaux de transmission des donnees"), ('330', '330 - Specialites plurivalentes sanitaires et sociales'), ('331', '331 - Sante'), ('332', '332 - Travail social'), ('333', '333 - Enseignement, formation'), ('334', '334 - Accueil, hotellerie, tourisme'), ('336', '336 - Coiffure, esthetique et autres specialites de services aux personnes'), ('343', "343 - Nettoyage, assainissement, protection de l'environnement"), ('344', '344 - Securite des biens et des personnes, police, surveillance')], help_text='Code NSF de specialite de formation pour le CERFA professionnalisation.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='specialite_formation',
            field=models.CharField(blank=True, choices=[('200', '200 - Technologies industrielles fondamentales'), ('201', '201 - Technologies de commandes des transformations industrielles'), ('221', '221 - Agro-alimentaire, alimentation, cuisine'), ('227', '227 - Energie, genie climatique'), ('230', '230 - Genie civil, construction, bois'), ('231', '231 - Mines et carrieres, genie civil, topographie'), ('232', '232 - Batiment : construction et couverture'), ('233', '233 - Batiment : finitions'), ('234', "234 - Travail du bois et de l'ameublement"), ('250', '250 - Specialites pluritechnologiques mecanique-electricite'), ('251', '251 - Mecanique generale et de precision, usinage'), ('252', '252 - Moteurs et mecanique auto'), ('255', '255 - Electricite, electronique'), ('310', '310 - Specialites plurivalentes des echanges et de la gestion'), ('311', '311 - Transport, manutention, magasinage'), ('312', '312 - Commerce, vente'), ('314', '314 - Comptabilite, gestion'), ('315', "315 - Ressources humaines, gestion du personnel, gestion de l'emploi"), ('320', '320 - Specialites plurivalentes de la communication'), ('321', '321 - Journalisme et communication'), ('326', "326 - Informatique, traitement de l'information, reseaux de transmission des donnees"), ('330', '330 - Specialites plurivalentes sanitaires et sociales'), ('331', '331 - Sante'), ('332', '332 - Travail social'), ('333', '333 - Enseignement, formation'), ('334', '334 - Accueil, hotellerie, tourisme'), ('336', '336 - Coiffure, esthetique et autres specialites de services aux personnes'), ('343', "343 - Nettoyage, assainissement, protection de l'environnement"), ('344', '344 - Securite des biens et des personnes, police, surveillance')], help_text='Code NSF à 3 chiffres utilisé pour la spécialité de formation dans le CERFA professionnalisation.', max_length=3, null=True, verbose_name='Code NSF spécialité de formation'),
        ),
    ]
