# Generated by Django 4.2.7 on 2026-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0047_formation_heures_enseignements_generaux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cerfacontrat",
            name="cfa_entreprise",
            field=models.BooleanField(
                default=True,
                help_text="Case indiquant si le CFA est un CFA d’entreprise.",
            ),
        ),
    ]
