# Generated by Django 4.2.7 on 2026-03-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0048_alter_cerfacontrat_cfa_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode1_debut',
            field=models.DateField(blank=True, help_text='Date de debut de la premiere periode de remuneration de 1ere annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode1_fin',
            field=models.DateField(blank=True, help_text='Date de fin de la premiere periode de remuneration de 1ere annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode1_pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage applique sur la premiere periode de remuneration de 1ere annee.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode1_reference',
            field=models.CharField(blank=True, help_text='Reference de base (SMIC/SMC) pour la premiere periode de remuneration de 1ere annee.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode2_debut',
            field=models.DateField(blank=True, help_text='Date de debut de la seconde periode de remuneration de 1ere annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode2_fin',
            field=models.DateField(blank=True, help_text='Date de fin de la seconde periode de remuneration de 1ere annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode2_pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage applique sur la seconde periode de remuneration de 1ere annee.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee1_periode2_reference',
            field=models.CharField(blank=True, help_text='Reference de base (SMIC/SMC) pour la seconde periode de remuneration de 1ere annee.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode1_debut',
            field=models.DateField(blank=True, help_text='Date de debut de la premiere periode de remuneration de 2eme annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode1_fin',
            field=models.DateField(blank=True, help_text='Date de fin de la premiere periode de remuneration de 2eme annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode1_pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage applique sur la premiere periode de remuneration de 2eme annee.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode1_reference',
            field=models.CharField(blank=True, help_text='Reference de base (SMIC/SMC) pour la premiere periode de remuneration de 2eme annee.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode2_debut',
            field=models.DateField(blank=True, help_text='Date de debut de la seconde periode de remuneration de 2eme annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode2_fin',
            field=models.DateField(blank=True, help_text='Date de fin de la seconde periode de remuneration de 2eme annee.', null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode2_pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage applique sur la seconde periode de remuneration de 2eme annee.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='remu_annee2_periode2_reference',
            field=models.CharField(blank=True, help_text='Reference de base (SMIC/SMC) pour la seconde periode de remuneration de 2eme annee.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='nombre_organismes_formation',
            field=models.PositiveIntegerField(blank=True, default=1, help_text="Nombre d'organismes de formation intervenant dans le contrat de professionnalisation.", null=True),
        ),
    ]
