# Generated by Django 4.2.7 on 2026-03-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0049_cerfacontrat_remu_annee1_periode1_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfacontrat',
            name='avantage_autre',
            field=models.CharField(blank=True, help_text='Autre avantage en nature, le cas echeant.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='avantage_logement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant de l'avantage en nature logement, en euros par mois.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cerfacontrat',
            name='avantage_nourriture',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant de l'avantage en nature nourriture, en euros par repas.", max_digits=8, null=True),
        ),
    ]
