# Generated by Django 4.2.7 on 2026-03-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0050_cerfacontrat_avantage_autre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfacontrat',
            name='nature_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('travail_temporaire', 'travail temporaire')], help_text='Nature du contrat pour le CERFA professionnalisation : CDI, CDD ou travail temporaire.', max_length=24, null=True),
        ),
    ]
