# Generated by Django 4.2.7 on 2026-04-10 19:33

import django.core.validators
from django.db import migrations, models
import rap_app.models.jury


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0053_importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrateur'), ('admin', 'Administrateur'), ('commercial', 'Commercial'), ('charge_recrutement', 'Chargé de recrutement'), ('staff', 'Membre du staff'), ('staff_read', 'Staff lecture seule'), ('prepa_staff', 'Staff PrépaComp'), ('declic_staff', 'Staff Déclic'), ('stagiaire', 'Stagiaire'), ('candidat', 'Candidat'), ('candidatuser', 'Candidat validé'), ('test', 'Test')], db_index=True, default='stagiaire', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='suivijury',
            name='annee',
            field=models.PositiveIntegerField(default=rap_app.models.jury.current_year, help_text='Année au format YYYY (ex: 2024)', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='suivijury',
            name='mois',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=rap_app.models.jury.current_month, help_text="Mois de l'année (1-12)", verbose_name='Mois'),
        ),
    ]
