# Generated by Django 4.2.7 on 2026-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0055_statut_formation_terminee"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="presents_en_formation",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre de personnes présentes en formation (saisie)",
                verbose_name="Présents en formation",
            ),
        ),
        migrations.AlterField(
            model_name="statut",
            name="nom",
            field=models.CharField(
                choices=[
                    ("non_defini", "Non défini"),
                    ("projet_de_developpement", "Projet de développement"),
                    ("a_recruter", "À recruter"),
                    ("recrutement_en_cours", "Recrutement en cours"),
                    ("formation_en_cours", "Formation en cours"),
                    ("formation_a_annuler", "Formation à annuler"),
                    ("formation_a_repousser", "Formation à repousser"),
                    ("formation_annulee", "Formation annulée"),
                    ("formation_terminee", "Formation terminée"),
                    ("pleine", "Pleine"),
                    ("quasi_pleine", "Quasi-pleine"),
                    ("autre", "Autre"),
                ],
                help_text="Identifiant du statut parmi les choix prédéfinis",
                max_length=100,
                verbose_name="Nom du statut",
            ),
        ),
    ]
