# Generated by Django 4.2.7 on 2026-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0056_formation_presents_en_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeoffre",
            name="nom",
            field=models.CharField(
                choices=[
                    ("crif", "CRIF"),
                    ("alternance", "Alternance"),
                    ("poec", "POEC"),
                    ("poei", "POEI"),
                    ("tosa", "TOSA"),
                    ("afc", "AFC"),
                    ("mp", "MP"),
                    ("autre", "Autre"),
                    ("non_defini", "Non défini"),
                ],
                default="non_defini",
                help_text="Sélectionnez le type d'offre de formation parmi les choix prédéfinis",
                max_length=100,
                verbose_name="Type d'offre",
            ),
        ),
    ]
