# Generated by Django 4.2.7 on 2026-04-24 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0058_plan_action_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planactionformation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Utilisateur ayant créé l'enregistrement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="planactionformation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Dernier utilisateur ayant modifié l'enregistrement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
    ]
