# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models


def backfill_saisi_par(apps, schema_editor):
    Partenaire = apps.get_model("rap_app", "Partenaire")
    User = apps.get_model("rap_app", "CustomUser")
    for p in Partenaire.objects.all().only("id", "created_by_id", "updated_by_id").iterator():
        to_add = []
        if p.created_by_id:
            to_add.append(p.created_by_id)
        if p.updated_by_id and p.updated_by_id not in to_add:
            to_add.append(p.updated_by_id)
        for uid in to_add:
            try:
                p.saisi_par.add(User.objects.get(pk=uid))
            except User.DoesNotExist:
                pass


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0059_alter_planactionformation_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partenaire",
            name="saisi_par",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tout compte qui a enregistré ce partenaire (création ou réutilisation d’un doublon). "
                "Permet à plusieurs candidats d’accéder à la même fiche sans se connaître.",
                related_name="partenaires_saisi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fiche saisie par",
            ),
        ),
        migrations.RunPython(backfill_saisi_par, reverse_noop),
    ]
