# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0060_partenaire_saisi_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="partenaire",
            name="retrait_de_vue_par",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comptes non créateurs qui ont retiré cette fiche de leur vue sans archivage global "
                "(le partenaire reste actif et visible pour les autres).",
                related_name="partenaires_masques_pour_moi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Retiré de la liste de",
            ),
        ),
    ]
