# Generated by Django 4.2.7 on 2026-04-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0061_partenaire_retrait_de_vue'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaireprepa',
            name='centre_afpa_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_prepa_orientes', to='rap_app.centre', verbose_name='Centre AFPA cible'),
        ),
        migrations.AddField(
            model_name='stagiaireprepa',
            name='date_orientation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'orientation"),
        ),
        migrations.AddField(
            model_name='stagiaireprepa',
            name='entree_formation_confirmee',
            field=models.BooleanField(default=False, verbose_name='Entrée en formation AFPA confirmée'),
        ),
        migrations.AddField(
            model_name='stagiaireprepa',
            name='formation_afpa_cible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Formation AFPA cible'),
        ),
        migrations.AddField(
            model_name='stagiaireprepa',
            name='orientation_finale',
            field=models.CharField(blank=True, choices=[('afpa', 'Orienté AFPA'), ('autre_centre_afpa', 'Orienté vers un autre centre AFPA'), ('hors_afpa', 'Autre orientation')], db_index=True, max_length=32, null=True, verbose_name='Orientation finale'),
        ),
        migrations.AddField(
            model_name='stagiaireprepa',
            name='prochain_atelier_prevu',
            field=models.CharField(blank=True, choices=[('info_collective', 'Information collective'), ('atelier_1', 'Atelier 1'), ('atelier_2', 'Atelier 2'), ('atelier_3', 'Atelier 3'), ('atelier_4', 'Atelier 4'), ('atelier_5', 'Atelier 5'), ('atelier_6', 'Atelier 6'), ('autre', 'Autre activité Prépa')], help_text='Atelier explicitement attendu ensuite, si le parcours a déjà été positionné.', max_length=40, null=True, verbose_name='Prochain atelier prévu'),
        ),
        migrations.AddField(
            model_name='stagiaireprepa',
            name='statut_positionnement',
            field=models.CharField(blank=True, choices=[('a_positionner', 'A positionner'), ('positionne', 'Positionné'), ('en_attente', 'En attente')], db_index=True, max_length=24, null=True, verbose_name='Statut de positionnement'),
        ),
        migrations.AddIndex(
            model_name='stagiaireprepa',
            index=models.Index(fields=['statut_positionnement'], name='rap_app_sta_statut__b9d8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaireprepa',
            index=models.Index(fields=['orientation_finale'], name='rap_app_sta_orienta_8897c2_idx'),
        ),
    ]
