# Generated by Django 4.2.7 on 2026-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0062_stagiaireprepa_centre_afpa_cible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospection",
            name="motif",
            field=models.CharField(
                choices=[
                    ("POEI", "POEI"),
                    ("apprentissage", "Alternance"),
                    ("VAE", "VAE"),
                    ("partenariat", "Établir un partenariat"),
                    ("autre", "Autre"),
                ],
                max_length=30,
                verbose_name="Motif",
            ),
        ),
        migrations.AlterField(
            model_name="prospection",
            name="objectif",
            field=models.CharField(
                choices=[
                    ("prise_contact", "Prise de contact"),
                    ("rendez_vous", "Obtenir un rendez-vous"),
                    ("presentation_offre", "Présentation d'une offre"),
                    ("candidature", "Candidature"),
                    ("contrat", "Signer un contrat"),
                    ("partenariat", "Établir un partenariat"),
                    ("autre", "Autre"),
                ],
                default="prise_contact",
                max_length=30,
                verbose_name="Objectif",
            ),
        ),
    ]
