# Generated by Django 4.2.7 on 2026-04-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0063_alter_prospection_motif_alter_prospection_objectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepa',
            name='date_debut_atelier',
            field=models.DateField(blank=True, help_text="Date de début effective de l'atelier quand elle diffère de la date principale.", null=True, verbose_name='Date de début atelier'),
        ),
        migrations.AddField(
            model_name='prepa',
            name='date_fin_atelier',
            field=models.DateField(blank=True, help_text="Date de fin effective de l'atelier quand elle diffère de la date principale.", null=True, verbose_name='Date de fin atelier'),
        ),
        migrations.AddField(
            model_name='prepa',
            name='nb_absents_prepa_hors_liste',
            field=models.PositiveIntegerField(default=0, verbose_name='Absents hors liste nominative'),
        ),
        migrations.AddField(
            model_name='prepa',
            name='nb_inscrits_prepa_hors_liste',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscrits hors liste nominative'),
        ),
        migrations.AddField(
            model_name='prepa',
            name='nb_presents_prepa_hors_liste',
            field=models.PositiveIntegerField(default=0, verbose_name='Présents hors liste nominative'),
        ),
        migrations.CreateModel(
            name='PrepaStagiaireParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent')], default='inscrit', max_length=16, verbose_name='Statut de participation')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire de présence')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('prepa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_stagiaires_prepa', to='rap_app.prepa', verbose_name='Séance Prépa')),
                ('stagiaire_prepa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_prepa', to='rap_app.stagiaireprepa', verbose_name='Stagiaire Prépa')),
                ('updated_by', models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Participation stagiaire Prépa',
                'verbose_name_plural': 'Participations stagiaires Prépa',
                'indexes': [models.Index(fields=['prepa', 'statut'], name='rap_app_pre_prepa_i_f97080_idx'), models.Index(fields=['stagiaire_prepa', 'statut'], name='rap_app_pre_stagiai_207cf1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='prepastagiaireparticipation',
            constraint=models.UniqueConstraint(fields=('prepa', 'stagiaire_prepa'), name='uniq_prepa_stagiaire_participation'),
        ),
    ]
