# Generated by Django 4.2.7 on 2026-04-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0064_prepa_date_debut_atelier_prepa_date_fin_atelier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepastagiaireparticipation',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent'), ('termine', 'Terminé')], default='inscrit', max_length=16, verbose_name='Statut de participation'),
        ),
    ]
