# Generated by Django 4.2.7 on 2026-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0065_alter_prepastagiaireparticipation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepastagiaireparticipation',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent'), ('termine', 'Terminé'), ('a_repositionner', 'À repositionner')], default='inscrit', max_length=16, verbose_name='Statut de participation'),
        ),
    ]
