# Generated by Django 4.2.7 on 2026-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rap_app", "0068_stagiaireprepa_centre_afpa_cible_texte"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stagiaireprepa",
            index=models.Index(
                fields=["issue_bilan"], name="rap_app_sta_issue_b_405021_idx"
            ),
        ),
    ]
