server {
    listen 80;
    server_name rap.adserv.fr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name rap.adserv.fr;

    ssl_certificate /etc/letsencrypt/live/rap.adserv.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rap.adserv.fr/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/rap_app_front;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /srv/rap_app/app/staticfiles/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /srv/rap_app/shared/media/;
        expires 7d;
    }
}
