// src/utils/breadcrumbLabels.ts
export const breadcrumbLabels: Record<string, string> = {
  dashboard: "Tableau de bord",
  prospection: "Prospections",
  "prospection-commentaires": "Commentaires Prospection",
  partenaires: "Partenaires",
  "appairage-commentaires": "Commentaires Appairage",
  appairages: "Appairages",
  candidats: "Candidats",
  "ateliers-tre": "Ateliers TRE",
  formations: "Formations",
  evenements: "Événements",
  rapports: "Rapports",
  logs: "Logs",
  declic: "Déclic",
  "participants-declic": "Participants Déclic",
  prepa: "Prépa",
  objectifs: "Objectifs",
  ic: "IC Prépa",
  ateliers: "Ateliers Prépa",
  stagiaires: "Stagiaires Prépa",
  commentaires: "Commentaires",
  documents: "Documents",
  parametres: "Paramètres",
  login: "Connexion",
};
